name: codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pytest --cov=my_utils test --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1